name: PR

on: pull_request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-release-ponyc-linux:
    name: Test against recent ponyc release on Linux
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/shared-docker-ci-x86-64-unknown-linux-builder:release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: add current ponyc packages dir to PONYPATH
        run: |
          ponyup show ponyc -b
          PONY_LOCATION=$(ponyup show ponyc -b | awk '{ print $1 }')
          echo "PONYPATH=$HOME/.local/share/ponyup/$PONY_LOCATION/packages:$PONYPATH" >> $GITHUB_ENV
      - name: tests debug
        run: make test config=debug
      - name: tests release
        run: make test config=release
